class animal

    name {get set}

    constructor(name)
        self.name = name
    end

    function testName(name)
        self.name = name
        if (#self.name > 100) then 
            print("that's a long name!")
        end
    end

end

class cat extends animal

    name {get set}

    constructor(name)
        self.name = name
    end

    function testName(name)
        self.name = name
        if (#self.name > 100) then 
            print("that's a long name!")
        end
    end

end

local function b() end

local b = new cat("Thomas")
print(b:getName())